### ISSUE TITLE
Feature request: CNAME support

### ISSUE THREAD

**Issue by phyzical** [Tarow/dockdns#1]
Hey neat little tool, any chance of adapting it to also work for cname records?

**Comment by Tarow** [comment]
Hey, thanks for the feedback.
I added CNAME support on this feature branch: https://github.com/Tarow/dockdns/tree/feature/cname-support

Feel free to test it out, the docker image is here: https://github.com/Tarow/dockdns/pkgs/container/dockdns/263042879?tag=feature-cname-support

**Comment by phyzical** [comment]
@Tarow thanks for the speedy implementation, thought it might have been straight forward looking at how you had designed it, but my limited go exp made me hold off 😆 

Can confirm its working exactly how i would like!

Only suggestion i have is maybe some clarity around what is cname and what is name, i had it backwards at first.

maybe something like `cname is the target for the cname record`

Besides like LGTM

**Comment by Tarow** [comment]
Fair point, i added some comments to the README :+1:
